
/usr/lib/python2.7/dist-packages/rpy2/rinterface/__init__.py:186: RRuntimeWarning: Loading required package: rngWELL

  warnings.warn(x, RRuntimeWarning)
/usr/lib/python2.7/dist-packages/rpy2/rinterface/__init__.py:186: RRuntimeWarning: This is randtoolbox. For an overview, type 'help("randtoolbox")'.

  warnings.warn(x, RRuntimeWarning)
expected = 2399670049798078.000000
actual = 2399670049798078.000000
expected = 2399670049798078.000000
actual = 2399670049798078.000000
expected = 2399670049798078.000000
actual = 2399670049798078.000000
expected = 0.000000
actual = 2399670049798078.000000
[00;31mERROR: orio.main.tuner.ptest_driver: failed to execute the test code: "timeout --kill-after=30s --signal=9 20m  ./__orio_perftest4.exe  "
 --> CalledProcessError: Command 'timeout --kill-after=30s --signal=9 20m  ./__orio_perftest4.exe  ' returned non-zero exit status 1[00m
[00;31mERROR: orio.main.tuner.ptest_driver:  performance testing failed: "timeout --kill-after=30s --signal=9 20m  ./__orio_perftest4.exe  "[00m
expected = 2399670049798078.000000
actual = 2399670049798078.000000
expected = 2399670049798078.000000
actual = 2399670049798078.000000
WARNING: orio.module.loop.submodule.tile.transformation: tile size 512 must be greater than the stride value 512; tile index = jjj
WARNING: orio.module.loop.submodule.tile.transformation: tile size 4 must be greater than the stride value 4; tile index = kkk
expected = 2399670049798078.000000
actual = 2399670049798078.000000
expected = 2399670049798078.000000
actual = 2399670049798078.000000
WARNING: orio.module.loop.submodule.tile.transformation: tile size 1024 must be greater than the stride value 1024; tile index = jjj
expected = 0.000000
actual = 2399670049798078.000000
[00;31mERROR: orio.main.tuner.ptest_driver: failed to execute the test code: "timeout --kill-after=30s --signal=9 20m  ./__orio_perftest9.exe  "
 --> CalledProcessError: Command 'timeout --kill-after=30s --signal=9 20m  ./__orio_perftest9.exe  ' returned non-zero exit status 1[00m
[00;31mERROR: orio.main.tuner.ptest_driver:  performance testing failed: "timeout --kill-after=30s --signal=9 20m  ./__orio_perftest9.exe  "[00m
expected = 2399670049798078.000000
actual = 2399670049798078.000000
expected = 2399670049798078.000000
actual = 2399670049798078.000000
expected = 2399670049798078.000000
actual = 2399670049798078.000000
expected = 2399670049798078.000000
actual = 2399670049798078.000000
expected = 0.000000
actual = 2399670049798078.000000
[00;31mERROR: orio.main.tuner.ptest_driver: failed to execute the test code: "timeout --kill-after=30s --signal=9 20m  ./__orio_perftest14.exe  "
 --> CalledProcessError: Command 'timeout --kill-after=30s --signal=9 20m  ./__orio_perftest14.exe  ' returned non-zero exit status 1[00m
[00;31mERROR: orio.main.tuner.ptest_driver:  performance testing failed: "timeout --kill-after=30s --signal=9 20m  ./__orio_perftest14.exe  "[00m
expected = 2399670049798078.000000
actual = 2399670049798078.000000
expected = 2399670049798078.000000
actual = 2399670049798078.000000
expected = 2399670049798078.000000
actual = 2399670049798078.000000
expected = 2399670049798078.000000
actual = 2399670049798078.000000
expected = 2399670049798078.000000
actual = 2399670049798078.000000
expected = 2399670049798078.000000
actual = 2399670049798078.000000
WARNING: orio.module.loop.submodule.tile.transformation: tile size 32 must be greater than the stride value 32; tile index = kkk
expected = 2399670049798078.000000
actual = 2399670049798078.000000
/usr/lib/python2.7/dist-packages/rpy2/rinterface/__init__.py:186: RRuntimeWarning: Joining, by = c("T1_Ie", "T1_Je", "T1_Ke", "T2_Ie", "T2_Je", "T2_Ke", "ACOPY_xe", "ACOPY_ye", "U1_Ie", "U_Ie", "U_Je", "U_Ke", "RT_Ie", "RT_Je", "RT_Ke", "SCRe", "VEC1e", "VEC2e")

  warnings.warn(x, RRuntimeWarning)
/usr/lib/python2.7/dist-packages/rpy2/rinterface/__init__.py:186: RRuntimeWarning: Loading required package: foreach

  warnings.warn(x, RRuntimeWarning)
/usr/lib/python2.7/dist-packages/rpy2/rinterface/__init__.py:186: RRuntimeWarning: Loading required package: iterators

  warnings.warn(x, RRuntimeWarning)
/usr/lib/python2.7/dist-packages/rpy2/rinterface/__init__.py:186: RRuntimeWarning: Loading required package: parallel

  warnings.warn(x, RRuntimeWarning)
/usr/lib/python2.7/dist-packages/rpy2/rinterface/__init__.py:186: RRuntimeWarning: Error in validObject(model, complete = TRUE) : 
  invalid class ‚Äúkm‚Äù object: the number of experiments must be larger than the spatial dimension

  warnings.warn(x, RRuntimeWarning)
/usr/lib/python2.7/dist-packages/rpy2/rinterface/__init__.py:186: RRuntimeWarning: In addition: 
  warnings.warn(x, RRuntimeWarning)
/usr/lib/python2.7/dist-packages/rpy2/rinterface/__init__.py:186: RRuntimeWarning: There were 26 warnings (use warnings() to see them)
  warnings.warn(x, RRuntimeWarning)
/usr/lib/python2.7/dist-packages/rpy2/rinterface/__init__.py:186: RRuntimeWarning: 

  warnings.warn(x, RRuntimeWarning)
Traceback (most recent call last):
  File "../../../orcc", line 27, in <module>
    orio.main.orio_main.start(sys.argv, orio.main.orio_main.C_CPP)
  File "/root/dlmt_spapt_experiments/orio/orio/main/orio_main.py", line 109, in start
    optimized_code_seq = odriver.optimizeCodeFrags(cfrags, True)
  File "/root/dlmt_spapt_experiments/orio/orio/main/opt_driver.py", line 45, in optimizeCodeFrags
    cur_seq = self.__optimizeCodeFrag(cf, perf_params)
  File "/root/dlmt_spapt_experiments/orio/orio/main/opt_driver.py", line 120, in __optimizeCodeFrag
    cfrag.cfrags)
  File "/root/dlmt_spapt_experiments/orio/orio/main/tuner/tuner.py", line 152, in tune
    best_perf_params, best_perf_cost = search_eng.search()
  File "/root/dlmt_spapt_experiments/orio/orio/main/tuner/search/search.py", line 133, in search
    best_coord,best_perf,search_time,speedup = self.searchBestCoord(startCoord)
  File "/root/dlmt_spapt_experiments/orio/orio/main/tuner/search/gpr/gpr.py", line 548, in searchBestCoord
    best_point, used_points = self.gpr()
  File "/root/dlmt_spapt_experiments/orio/orio/main/tuner/search/gpr/gpr.py", line 513, in gpr
    best_predicted_points = robjects.r(r_snippet)
  File "/usr/lib/python2.7/dist-packages/rpy2/robjects/__init__.py", line 362, in __call__
    res = self.eval(p)
  File "/usr/lib/python2.7/dist-packages/rpy2/robjects/functions.py", line 178, in __call__
    return super(SignatureTranslatedFunction, self).__call__(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/rpy2/robjects/functions.py", line 106, in __call__
    res = super(Function, self).__call__(*new_args, **new_kwargs)
rpy2.rinterface.RRuntimeError: Error in validObject(model, complete = TRUE) : 
  invalid class ‚Äúkm‚Äù object: the number of experiments must be larger than the spatial dimension

